mappings:
  - match: "airflow.dagrun.duration.*.*"
    name: "airflow_dagrun_duration"
    labels:
      dag_id: "$1"
      status: "$2"
  - match: "airflow.dag_processing.total_parse_time"
    name: "airflow_dag_processing_total_parse_time"
  - match: "airflow.executor.queued_tasks"
    name: "airflow_executor_queued_tasks"
  - match: "airflow.executor.running_tasks"
    name: "airflow_executor_running_tasks"
  - match: "airflow.pool.open_slots.*"
    name: "airflow_pool_open_slots"
    labels:
      pool: "$1"
  - match: "airflow.pool.running_slots.*"
    name: "airflow_pool_running_slots"
    labels:
      pool: "$1"
  - match: "airflow.scheduler.heartbeat"
    name: "airflow_scheduler_heartbeat"
  - match: "airflow.ti.successes"
    name: "airflow_ti_successes"
  - match: "airflow.ti.failures"
    name: "airflow_ti_failures"
  - match: "airflow.*"
    name: "airflow_other"
    labels:
      metric: "$1"
